// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYWtWxY9wNX5AcAo8qFP7x99gKFiSxmpQ',
    appId: '1:720932734922:web:8fe7ff03d80d29d5ae7133',
    messagingSenderId: '720932734922',
    projectId: 'chatapp-c1016',
    authDomain: 'chatapp-c1016.firebaseapp.com',
    storageBucket: 'chatapp-c1016.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4gIqBH9et9OlLqx2aa-JNJ2ciwMybi1E',
    appId: '1:720932734922:android:ab5199d9e4125c39ae7133',
    messagingSenderId: '720932734922',
    projectId: 'chatapp-c1016',
    storageBucket: 'chatapp-c1016.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm0v6nGEZd01dgbhrXJ2oHYBvqdab-KyU',
    appId: '1:720932734922:ios:a40de45ee7ccb6abae7133',
    messagingSenderId: '720932734922',
    projectId: 'chatapp-c1016',
    storageBucket: 'chatapp-c1016.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm0v6nGEZd01dgbhrXJ2oHYBvqdab-KyU',
    appId: '1:720932734922:ios:a40de45ee7ccb6abae7133',
    messagingSenderId: '720932734922',
    projectId: 'chatapp-c1016',
    storageBucket: 'chatapp-c1016.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYWtWxY9wNX5AcAo8qFP7x99gKFiSxmpQ',
    appId: '1:720932734922:web:3f8f2b921b837bcbae7133',
    messagingSenderId: '720932734922',
    projectId: 'chatapp-c1016',
    authDomain: 'chatapp-c1016.firebaseapp.com',
    storageBucket: 'chatapp-c1016.firebasestorage.app',
  );
}
